# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ag', 'anger'), ('sd', 'sadness'), ('jy', 'joy'), ('dc', 'discust'), ('fr', 'fear')], default='jy', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('activity', models.ManyToManyField(to='tif.Activity')),
                ('feeling', models.ManyToManyField(to='tif.Feeling')),
                ('memo', models.ManyToManyField(to='tif.Memo')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.ManyToManyField(to='tif.Time'),
        ),
    ]
