# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
