# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='report',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tif.Report'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='tif.Activity'),
        ),
        migrations.AlterField(
            model_name='time',
            name='feeling',
            field=models.ManyToManyField(blank=True, null=True, to='tif.Feeling'),
        ),
        migrations.AlterField(
            model_name='time',
            name='memo',
            field=models.ManyToManyField(blank=True, null=True, to='tif.Memo'),
        ),
    ]
