# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0002_auto_20170621_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, related_name='activity_set', to='tif.Activity'),
        ),
        migrations.AlterField(
            model_name='time',
            name='feeling',
            field=models.ManyToManyField(blank=True, null=True, related_name='feeling_set', to='tif.Feeling'),
        ),
    ]
