# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0002_auto_20170525_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='category',
        ),
        migrations.AddField(
            model_name='feeling',
            name='feeling',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
