# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0002_remove_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
