# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0003_auto_20170622_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='tif.Activity'),
        ),
        migrations.AlterField(
            model_name='time',
            name='feeling',
            field=models.ManyToManyField(blank=True, null=True, to='tif.Feeling'),
        ),
    ]
