# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0003_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='memo',
        ),
        migrations.AddField(
            model_name='memo',
            name='time',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, related_name='time_memo', to='tif.Time'),
            preserve_default=False,
        ),
    ]
