# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tif', '0004_auto_20170527_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
